import { AlertTriangle, BarChart3, CloudRain, Map, Menu, RadioTower, Route, Satellite, Settings, ShieldAlert, Siren, UsersRound, X } from 'lucide-react'
import { NavLink, useLocation } from 'react-router-dom'
import { useState } from 'react'
import { OfflineStatus } from '../components/OfflineStatus'

const nav = [
  ['/dashboard', 'Command center', Map], ['/risk-map', 'Risk map', ShieldAlert], ['/reports', 'Reports', AlertTriangle], ['/alerts', 'Alerts', Siren], ['/roads', 'Road connectivity', Route], ['/emergency', 'Emergency response', UsersRound], ['/weather', 'Weather', CloudRain], ['/satellite', 'Satellite', Satellite], ['/sensors', 'Sensors', RadioTower], ['/analytics', 'Analytics', BarChart3], ['/settings', 'Settings', Settings],
] as const

export function AppShell({ children }: { children: React.ReactNode }) { const [open, setOpen] = useState(false); const location = useLocation(); return <div className="app-shell"><aside className={`sidebar ${open ? 'sidebar-open' : ''}`}><div className="brand"><span className="brand-mark">N</span><div><b>NER-LENS</b><small>Early warning platform</small></div><button className="close-nav" onClick={() => setOpen(false)} aria-label="Close navigation"><X size={18}/></button></div><div className="district-chip">NORTHEAST INDIA <i>DEMO</i></div><nav>{nav.map(([to, label, Icon]) => <NavLink onClick={() => setOpen(false)} key={to} to={to} className={({isActive}) => isActive ? 'active' : ''}><Icon size={17}/><span>{label}</span></NavLink>)}</nav><div className="sidebar-footer"><span className="pulse"/> Dashboard live via WebSocket</div></aside><main className="workspace"><header className="topbar"><button className="mobile-menu" onClick={() => setOpen(true)} aria-label="Open navigation"><Menu size={20}/></button><div><span className="breadcrumb">NER-LENS / {location.pathname.split('/').filter(Boolean).join(' / ') || 'overview'}</span><h1>{location.pathname === '/dashboard' ? 'Situation overview' : 'Landslide intelligence'}</h1></div><div className="top-actions"><OfflineStatus/><NavLink to="/login" className="user-button"><span>DA</span><b>Demo Access</b></NavLink></div></header>{children}</main></div> }
