import { useState } from 'react'
import { AlertTriangle, ArrowUpRight, BellRing, CloudRain, LoaderCircle, Route, Satellite, ShieldAlert, TriangleAlert, UsersRound } from 'lucide-react'
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { useDashboardData } from '../hooks/useDashboardData'
import { RiskMap } from '../maps/RiskMap'
import { ZoneDetail } from '../components/ZoneDetail'
import { KpiCard } from '../components/KpiCard'
import { ForecastStrip } from '../components/ForecastStrip'
import { RiskBadge } from '../components/RiskBadge'
import { api } from '../services/api'
import type { Zone } from '../types'

export function DashboardPage() { const data = useDashboardData(); const [selected, setSelected] = useState<Zone | undefined>(); const [simulating, setSimulating] = useState(false); const [simulationMessage, setSimulationMessage] = useState(''); const [error, setError] = useState('')
  const startSimulation = async () => { setSimulating(true); setError(''); try { await api.post('/api/simulation/start?scenario=critical_warning'); setSimulationMessage('Simulation active — rainfall, soil moisture, alerts and priority queue have been recalculated.'); await data.refresh() } catch (e: any) { setError(e.response?.status === 401 ? 'Sign in with the demo administrator account to start a controlled simulation.' : 'Unable to start simulation. Check the API service.') } finally { setSimulating(false) } }
  if (data.loading) return <div className="loading-screen"><LoaderCircle className="spin"/> Loading operational picture…</div>
  return <div className="dashboard-page"><div className="demo-banner"><Satellite size={15}/><span><b>DEMO / SIMULATED DATA</b> — Data flows are deterministic prototype data. Predictions are not guaranteed events.</span><button onClick={startSimulation} disabled={simulating}>{simulating ? 'Starting…' : 'START DISASTER SIMULATION'} <ArrowUpRight size={14}/></button></div>{(data.error || error) && <div className="error-banner"><AlertTriangle size={16}/>{data.error || error}</div>}{simulationMessage && <div className="success-banner">{simulationMessage}</div>}
    <section className="kpi-grid"><KpiCard label="Critical zones" value={data.stats?.critical_zones || 0} icon={TriangleAlert} accent="#e25050"/><KpiCard label="High risk zones" value={data.stats?.high_risk_zones || 0} icon={ShieldAlert} accent="#ed8b4d"/><KpiCard label="Open alerts" value={data.stats?.open_alerts || 0} icon={BellRing} accent="#eebd4d"/><KpiCard label="Roads at risk" value={data.stats?.roads_at_risk || 0} icon={Route} accent="#e48a52"/><KpiCard label="Field reports" value={data.stats?.active_field_reports || 0} icon={UsersRound} accent="#54a9de"/></section>
    <section className="command-grid"><div className="map-panel"><div className="section-heading"><div><span className="eyebrow">LIVE RISK MAP</span><h2>North East operational view</h2></div><span className="live-dot">LIVE</span></div><RiskMap zones={data.zones} roads={data.roads} selectedZone={selected} onSelect={setSelected}/></div><ZoneDetail zone={selected || data.zones[0]}/></section>
    <ForecastStrip forecast={data.forecast}/>
    <section className="bottom-grid"><div className="card chart-card"><div className="section-heading"><div><span className="eyebrow">RISK TREND</span><h2>Regional risk index</h2></div><b>+19% <small>24h</small></b></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.trend}><defs><linearGradient id="riskGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#e68a4e" stopOpacity=".42"/><stop offset="100%" stopColor="#e68a4e" stopOpacity="0"/></linearGradient></defs><XAxis dataKey="hour" tickLine={false} axisLine={false}/><YAxis domain={[0,100]} tickLine={false} axisLine={false}/><Tooltip/><Area dataKey="risk" stroke="#ed8b4d" strokeWidth={3} fill="url(#riskGradient)"/></AreaChart></ResponsiveContainer></div></div>
      <div className="card priority-card"><div className="section-heading"><div><span className="eyebrow">EMERGENCY PRIORITY</span><h2>Response queue</h2></div><a href="/emergency">View all</a></div>{data.zones.slice(0,3).map((zone, i) => <div className="priority-row" key={zone.id}><div className="priority-number">0{i+1}</div><div><b>{zone.zone_name}</b><span>{zone.district} · population exposure {zone.risk_score > 70 ? 'High' : 'Moderate'}</span></div><div><RiskBadge level={zone.risk_level}/><strong>{zone.risk_score}</strong></div></div>)}</div>
      <div className="card alerts-card"><div className="section-heading"><div><span className="eyebrow">ACTIVE ALERTS</span><h2>Attention required</h2></div><a href="/alerts">All alerts</a></div>{data.alerts.slice(0,2).map(alert => <div className="alert-row" key={alert.id}><RiskBadge level={alert.severity}/><div><b>{alert.title}</b><span>{alert.target_area} · demo notification</span></div></div>)}</div>
    </section></div> }
