import { useEffect, useState } from 'react'
import { Activity, AlertTriangle, BarChart3, BellRing, CloudRain, Cpu, Database, RadioTower, Route, Satellite, ShieldCheck, UsersRound } from 'lucide-react'
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Link } from 'react-router-dom'
import { api, getAlerts, getForecast, getRoads } from '../services/api'
import { RiskBadge } from '../components/RiskBadge'
import type { Alert, Road } from '../types'

const dataNotice = <div className="data-notice">DEMO / SIMULATED DATA — no external weather, satellite, SMS, or email provider is connected.</div>
export function AlertsPage() { const [alerts, setAlerts] = useState<Alert[]>([]); useEffect(() => { getAlerts().then(setAlerts).catch(() => undefined) }, []); return <div className="operations-page"><div className="page-intro"><span className="eyebrow">PUBLIC + AUTHORITY ALERTS</span><h2>Warning distribution center</h2><p>In-app alerts are functional. External delivery is deliberately labelled as demo until a provider is configured.</p></div>{dataNotice}<section className="stacked-list card">{alerts.map(alert => <article className="alert-detail" key={alert.id}><RiskBadge level={alert.severity}/><div><h3>{alert.title}</h3><p>{alert.message}</p><span>{alert.target_area} · {new Date(alert.created_at).toLocaleString()}</span></div><BellRing/></article>)}</section></div> }

export function RoadsPage() { const [roads, setRoads] = useState<Road[]>([]); const [message, setMessage] = useState(''); const [password, setPassword] = useState(''); useEffect(() => { getRoads().then(setRoads).catch(() => undefined) }, []); const update = async (road: Road, status: Road['status']) => { try { await api.patch(`/api/roads/${road.id}`, {status}); setRoads(await getRoads()); setMessage(`${road.road_name} is now ${status}.`) } catch (error: any) { setMessage(error.response?.status === 401 ? 'Sign in as a field officer, district authority, or administrator before updating road status.' : 'Unable to save road status.') } }; return <div className="operations-page"><div className="page-intro"><span className="eyebrow">NETWORK SAFETY</span><h2>Road connectivity</h2><p>Update access routes; blocked critical roads create an emergency task automatically.</p></div>{dataNotice}<section className="roads-table card"><div className="table-head"><span>Road</span><span>Classification</span><span>Status</span><span>Operational action</span></div>{roads.map(road => <div className="table-row" key={road.id}><b>{road.road_name}</b><span>{road.road_type} · Criticality {road.criticality.toFixed(2)}</span><RiskBadge level={road.status === 'PARTIALLY_BLOCKED' ? 'HIGH' : road.status === 'MONITORING' ? 'MODERATE' : road.status === 'BLOCKED' ? 'CRITICAL' : 'LOW'}/><select value={road.status} onChange={e => update(road, e.target.value as Road['status'])}><option>OPEN</option><option>MONITORING</option><option>PARTIALLY_BLOCKED</option><option>BLOCKED</option></select></div>)}</section>{message && <div className="form-message">{message}</div>}</div> }

export function EmergencyPage() { const [items, setItems] = useState<any[]>([]); useEffect(() => { api.get('/api/dashboard/priorities').then(r => setItems(r.data.priorities)).catch(() => undefined) }, []); return <div className="operations-page"><div className="page-intro"><span className="eyebrow">EMERGENCY RESPONSE</span><h2>Prioritized response queue</h2><p>Priority combines landslide risk with population exposure, infrastructure, connectivity, and response difficulty.</p></div>{dataNotice}<section className="priority-list card">{items.map((item, index) => <article key={item.id} className="emergency-item"><div className="priority-rank">{String(index+1).padStart(2,'0')}</div><div><RiskBadge level={item.priority}/><h3>{item.priority} operational task</h3><p>{item.explanation}</p><span>{item.assigned_team || 'No team assigned'} · {item.status}</span></div><strong>{item.priority_score}<small>/100</small></strong></article>)}</section></div> }

export function WeatherPage() { const [forecast, setForecast] = useState<any[]>([]); useEffect(() => { getForecast().then(setForecast).catch(() => undefined) }, []); return <div className="operations-page"><div className="page-intro"><span className="eyebrow">WEATHER INTELLIGENCE</span><h2>Rainfall forecast</h2><p>Mock WeatherProvider is active. Credentials can switch the backend to a live provider.</p></div>{dataNotice}<div className="weather-grid">{forecast.map(item => <div className="weather-card card" key={item.horizon}><CloudRain/><span>{item.horizon}</span><b>{item.rainfall_mm} mm</b><small>{item.condition}</small></div>)}</div></div> }

export function SatellitePage() { const [observations, setObservations] = useState<any[]>([]); useEffect(() => { api.get('/api/satellite/observations').then(r => setObservations(r.data.observations)).catch(() => undefined) }, []); return <div className="operations-page"><div className="page-intro"><span className="eyebrow">SATELLITE ANALYSIS</span><h2>Change detection monitor</h2><p>Satellite analysis: Demo mode. The pipeline is ready for a provider integration.</p></div><div className="pipeline"><span>Satellite image</span><i>→</i><span>Preprocess</span><i>→</i><span>Compare</span><i>→</i><span>Change score</span><i>→</i><span>Risk engine</span></div><section className="stacked-list card">{observations.map(o => <article className="satellite-row" key={o.id}><Satellite/><div><b>Location {o.location_id} · {o.landslide_indicator.replace('_',' ')}</b><span>Observation {new Date(o.observation_date).toLocaleDateString()} · Demo observation</span></div><div><b>{o.change_score}</b><small>change score</small></div><div><b>{o.deformation_score}</b><small>deformation</small></div></article>)}</section></div> }

export function SensorsPage() { const [result, setResult] = useState(''); const [form, setForm] = useState({sensor_id:'SM001',latitude:'23.727',longitude:'92.717',soil_moisture:'78.3'}); const send = async () => { try { const r = await api.post('/api/sensors/data', {...form, latitude:Number(form.latitude), longitude:Number(form.longitude), soil_moisture:Number(form.soil_moisture), timestamp:new Date().toISOString()}); setResult(`Sensor accepted. Nearest zone: ${r.data.nearest_zone}. Risk has been recalculated.`) } catch { setResult('Unable to submit sensor data. Check numeric fields and backend availability.') } }; return <div className="operations-page"><div className="page-intro"><span className="eyebrow">SENSOR INTEGRATION</span><h2>Ingest a field reading</h2><p>Send a validated sensor payload; the closest demo zone recalculates immediately.</p></div>{dataNotice}<section className="sensor-card card"><RadioTower/><div><h3>POST /api/sensors/data</h3><p>Use this form to drive the real sensor ingestion contract during a demo.</p></div><div className="sensor-form">{Object.entries(form).map(([key, value]) => <label key={key}>{key.replace('_',' ')}<input value={value} onChange={e=>setForm(v=>({...v,[key]:e.target.value}))}/></label>)}<button className="primary-button" onClick={send}>Send reading</button></div>{result && <div className="form-message">{result}</div>}</section></div> }

export function AnalyticsPage() { const data = [{name:'Rainfall 24h',value:31},{name:'Soil moisture',value:24},{name:'Slope',value:18},{name:'History',value:14},{name:'Land cover',value:9},{name:'Road distance',value:4}]; return <div className="operations-page"><div className="page-intro"><span className="eyebrow">MODEL MONITORING</span><h2>Baseline model transparency</h2><p>Performance values are training estimates from the synthetic demo dataset, not production validation.</p></div>{dataNotice}<section className="model-grid"><div className="model-card card"><Cpu/><h3>Random Forest demo baseline</h3><span>Version 0.1 · trained locally</span><div className="metrics"><b>0.89 <small>Accuracy</small></b><b>0.86 <small>Precision</small></b><b>0.84 <small>Recall</small></b><b>0.85 <small>F1</small></b><b>0.91 <small>ROC-AUC</small></b></div></div><div className="importance-chart card"><h3>Feature importance</h3><ResponsiveContainer width="100%" height={255}><BarChart data={data} layout="vertical"><CartesianGrid strokeDasharray="3 3"/><XAxis type="number"/><YAxis dataKey="name" type="category" width={100}/><Tooltip/><Bar dataKey="value" fill="#e78b50" radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></div></section></div> }

export function SettingsPage() { return <div className="operations-page"><div className="page-intro"><span className="eyebrow">SYSTEM CONFIGURATION</span><h2>Operational settings</h2><p>Provider keys stay in the backend environment; they are never exposed to this interface.</p></div><section className="settings-card card"><Database/><div><h3>Demo Mode</h3><p>Using deterministic local weather, sensor, satellite and notification abstractions.</p></div><span className="enabled-pill">ENABLED</span><ShieldCheck/><div><h3>Localization</h3><p>English and Hindi templates are ready; Assamese, Bengali, Mizo, Khasi, Manipuri, Nepali and Tripuri are extensible.</p></div><Link className="secondary-button" to="/users">Manage demo users</Link></section></div> }

export function UsersPage() { const [users, setUsers] = useState<any[]>([]); const [message, setMessage] = useState(''); const load = () => api.get('/api/users').then(r => setUsers(r.data.users)).catch((error: any) => setMessage(error.response?.status === 401 || error.response?.status === 403 ? 'Sign in as the administrator to manage user roles.' : 'Unable to load user records.')); useEffect(() => { load() }, []); const update = async (id: number, role: string) => { try { await api.patch(`/api/users/${id}`, {role}); setMessage('Role updated. The dashboard has been notified.'); load() } catch { setMessage('Role change was not saved. Administrator access is required.') } }; return <div className="operations-page"><div className="page-intro"><span className="eyebrow">ADMINISTRATION</span><h2>User management</h2><p>Assign the four prototype roles used for the authorization workflow.</p></div><section className="roads-table card"><div className="table-head"><span>Name</span><span>Email</span><span>District</span><span>Role</span></div>{users.map(user => <div className="table-row" key={user.id}><b>{user.name}</b><span>{user.email}</span><span>{user.district || '—'}</span><select value={user.role} onChange={e => update(user.id, e.target.value)}>{['ADMIN','DISTRICT_AUTHORITY','FIELD_OFFICER','CITIZEN'].map(role => <option key={role}>{role}</option>)}</select></div>)}</section>{message && <div className="form-message">{message}</div>}</div> }
